@startuml

autonumber

' View config
' skinparam dpi 300
skinparam monochrome true
skinparam shadowing false
skinparam sequenceParticipant underline

skinparam defaultFontName Arial
skinparam defaultFontSize 10
skinparam defaultFontStyle italic

skinparam SequenceMessageAlign center

skinparam SequenceArrowThickness 1
skinparam SequenceDividerBorderThickness 1
skinparam SequenceGroupBorderThickness 1
skinparam SequenceLifeLineBorderThickness 1
skinparam SequenceParticipantBorderThickness 1
skinparam SequenceReferenceBorderThickness 1
skinparam SequenceParticipantBackgroundColor White
skinparam SequenceBoxBackgroundColor White
skinparam SequenceGroupBackgroundColor White

skinparam ParticipantPadding 50

skinparam MinClassWidth 80

hide footbox
' title Footer removed

' Renaming titles
!define user "Пользователь"
!define s_zeppelin "Сервер Zeppelin"
!define s_zookeeper "Сервер ZooKeeper"
!define s_kafka "Брокер Kafka"
!define s_master "Spark Master"
!define s_worker "Spark Worker Node"
!define s_par_spark "Параграф Spark"
!define s_window "Окно обработки"
!define s_rdd "RDD"
!define s_par_angular "Параграф Angular"

'Grouping
'box "Каждое ядро системы" #White
'	participant local_bench
'   participant curr_load
' 	participant tirtos
' 	participant ipc
'end box

' participant multiproc_buff

' box "Главное ядро системы" #White
' 	participant g_ipc
' 	participant g_bench
'     participant g_ws
' 	participant g_tirtos
' end box

' Diagram
user -> s_zeppelin: Запуск Zeppelin
activate s_zeppelin

s_zeppelin -> s_zeppelin: Инициализация интерпретатора

s_zeppelin -> s_par_spark: Запуск параграфа
activate s_par_spark

s_par_spark -> s_zookeeper: Подключение к kafka
activate s_zookeeper

s_zookeeper -> s_kafka: Получение статуса брокеров
activate s_kafka

return Статус брокера
return Подтвержение подключения

s_par_spark -> s_window: Создание окна
activate s_window

alt Пока в окне
    s_par_spark -> s_kafka: Получение сообщений
    return Сообщение
    s_par_spark -> s_window: Агрегация сообщений
end
s_window -> s_par_spark: Окно сообщений

s_par_spark -> s_rdd: Создание RDD
activate s_rdd

s_rdd -> s_rdd: Обработка значений
return Список индексов

s_par_spark -> s_par_angular: Отображение результата

deactivate s_par_spark

@enduml
