@startuml

autonumber

' View config
' skinparam dpi 300
skinparam monochrome true
skinparam shadowing false
skinparam sequenceParticipant underline

skinparam defaultFontName Arial
skinparam defaultFontSize 10
skinparam defaultFontStyle italic

skinparam SequenceMessageAlign center

skinparam SequenceArrowThickness 1
skinparam SequenceDividerBorderThickness 1
skinparam SequenceGroupBorderThickness 1
skinparam SequenceLifeLineBorderThickness 1
skinparam SequenceParticipantBorderThickness 1
skinparam SequenceReferenceBorderThickness 1
skinparam SequenceParticipantBackgroundColor White
skinparam SequenceBoxBackgroundColor White
skinparam SequenceGroupBackgroundColor White

skinparam ParticipantPadding 50

skinparam MinClassWidth 80

hide footbox
' title Footer removed

' Renaming titles
!define local_bench "Модуль локального сбора статистики"
!define curr_load "Структура текущей загрузки"
!define tirtos "TI-RTOS"
!define ipc "Модуль межъядерного взаимодействия"
!define multiproc_buff "Буфер для пересылки межъядерных сообщений"
!define multiproc_buff_part "Сообщение"
!define g_ipc "Модуль межъядерного взаимодействия на главном ядре"
!define g_tirtos "TI-RTOS на главном ядре"
!define g_bench "Модуль глобального сбора статистики"
!define g_ws "Модуль сервера веб-сокетов"

' Grouping
' box "Каждое ядро системы" #White
' 	participant local_bench
'     participant curr_load
' 	participant tirtos
' 	participant ipc
' end box

' participant multiproc_buff

' box "Главное ядро системы" #White
' 	participant g_ipc
' 	participant g_bench
'     participant g_ws
' 	participant g_tirtos
' end box

' Diagram
[-> local_bench : Информация готова
activate local_bench

create curr_load
local_bench -> curr_load : Создание структуры загрузки

local_bench -> curr_load : Инициализация
activate curr_load

curr_load -> tirtos : Получить текущее время
activate tirtos
return Текущее время

curr_load -> curr_load : Получить текущую загрузку
activate curr_load

curr_load -> tirtos : Получить загрузку по аппаратным прерываниям
activate tirtos

return Загрузка

curr_load -> tirtos : Получить загрузку по программным прерываниям
activate tirtos

return Загрузка

loop Все задачи на ядре
    curr_load -> tirtos : Получить загрузку по задаче
    activate tirtos

    return Загрузка
end

return Структура загрузки ядра

curr_load -> tirtos : Получить имя ядра
activate tirtos
return Имя ядра

return Инициализация завершена

alt Инициализация источника межъядерных сообщений не проведена
    local_bench -> ipc : Проинициализировать источник сообщений
    activate ipc

    alt Успешная инициализация
        return Инициализация прошла успешно
    else Возникла ошибка
        ipc -> local_bench : Ошибка
    end
end

alt Инициализация источника межъядерных сообщений проведена
    local_bench -> ipc : Отправить структуру
    activate ipc

    ipc -> ipc : Расчет требуемого места для передачи сообщения
    activate ipc
    return Требуется x байт

    ipc -> multiproc_buff : Выделение x байт для передачи сообщения
    activate multiproc_buff

    create multiproc_buff_part

    alt Доступно свободное место требуемого размера

    multiproc_buff -> multiproc_buff_part : Выделение буфера

    return Указатель на выделенный буфер

        ipc -> multiproc_buff_part : Записать заголовок межъядерного сообщения
        activate multiproc_buff_part
        return Сообщение обновлено

        ipc -> multiproc_buff_part : Записать сообщение для отправки
        activate multiproc_buff_part
        return Сообщение обновлено

        ipc -> multiproc_buff : Отправить сообщение на главное ядро
        activate multiproc_buff
        return Статус отправки сообщения

        return Статус отправки сообщения

    else Недостаточно свободного места
        multiproc_buff -> ipc : NULL
        ipc -> local_bench : Ошибка выделения памяти сообщения
    end

end

local_bench -> curr_load : Удалить объект

destroy curr_load

deactivate local_bench

@enduml
