version: '2.1'
services:
  zookeeper:
    container_name: zookeeper
    image: wurstmeister/zookeeper
    ports:
      - 2181:2181

  kafka:
    container_name: kafka
    image: wurstmeister/kafka
    hostname: kafka
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "co-topic:1:1,so-topic:1:1,oz-topic:1:1,no-topic:1:1"
    depends_on:
      - zookeeper
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9092"]
      interval: 30s
      timeout: 10s
      retries: 5

  zeppelin:
    build: ./zeppelin/
    container_name: zeppelin
    environment:
      ZEPPELIN_PORT: 8090
      ZEPPELIN_JAVA_OPTS: >-
        -Dspark.driver.memory=1g
        -Dspark.executor.memory=2g
      MASTER: "local[*]"
    ports:
      - 8090:8090
    expose:
      - 9092
    links:
      - kafka
    volumes:
      - ./zeppelin/data:/zeppelin/data
      - ./zeppelin/notebook:/zeppelin/notebook
      - ./zeppelin/logs:/zeppelin/logs
      - ./spark/output:/zeppelin/data/shared
  
  dumper:
    build: ../OAPM/
    container_name: dumper
    expose:
      - 9092
    links:
      - kafka
    volumes:
      - ./dumper/output:/output
    depends_on:
      - kafka
      - zeppelin

  oap-spark-app:
    build: ../OAPSpark/
    depends_on:
      - kafka
    environment:
      - "SPARK_MASTER=local[*]"
      - "SPARK_WORKER_WEBUI_PORT=8081"      
    volumes:
      - ./spark/output:/shared
    command: "/startDocker.sh"

